---
- name: Install Httpd and configure service
  hosts: all
  become: yes
  
  tasks:
    - name: Install httpd
      apt:
        name: apache2
        state: present
    
    - name: Change Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'

    - name: Update Apache VirtualHost to use port 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'

    - name: Run service
      service:
        name: apache2
        state: restarted
        enabled: yes
